services:
  api:
    image: stellar-lab-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      ENVIRONMENT: development
      PORT: ${PORT:-3000}

      # DB Connection
      #   - Mode A: Direct database URL
      DATABASE_URL: "postgresql://marcelosantos@host.docker.internal:5432/lab-backend-testnet"
      #   - Mode B: Cloud SQL Connector with IAM
      # DB Connection (Mode B)
      # DB_NAME: "postgres"
      # POSTGRES_CONNECTION_NAME: "hubble-261722:us-central1:ledger-data"
      # POSTGRES_IAM_USER: "ledger-data-indexer-api-prod-r@hubble-261722.iam"
      # POSTGRES_IAM_USER_URL_ENCODED: "ledger-data-indexer-api-prod-r%40hubble-261722.iam"
      # GOOGLE_APPLICATION_CREDENTIALS: "./creds.json"
      # GOOGLE_CLOUD_SQL_IP_TYPE: "PUBLIC"

    volumes:
      # `creds.json` must exist in the directory where you run docker-compose up (the project root):
      - ./creds.json:/app/creds.json:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
