name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-and-push-sha-tagged-image:
    name: Build and push a sha tagged container image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: make docker-build
      - name: Push image to DockerHub
        run: make docker-push
  build-and-push-release-image:
    name: Build and push a release tagged container image
    runs-on: ubuntu-24.04
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v5
      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        env:
          TAG: stellar/laboratory-backend:${{ github.event.release.tag_name }}
        run: make docker-build
      - name: Tag image as latest
        run: docker tag stellar/laboratory-backend:${{ github.event.release.tag_name }} stellar/laboratory-backend:latest
      - name: Push image to DockerHub
        env:
          TAG: stellar/laboratory-backend:${{ github.event.release.tag_name }}
        run: make docker-push
      - name: Push latest image to DockerHub
        env:
          TAG: stellar/laboratory-backend:latest
        run: make docker-push
